# Generated by Django 6.0.3 on 2026-04-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_address_business_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='menu_background',
            field=models.ImageField(blank=True, null=True, upload_to='menu_backgrounds/'),
        ),
        migrations.AddField(
            model_name='business',
            name='menu_text_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
