# Generated by Django 6.0.3 on 2026-04-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_menu_background_business_menu_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
