# Generated by Django 6.0.3 on 2026-04-06 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_table_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='session_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
