# Generated by Django 6.0.3 on 2026-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_id',
            field=models.CharField(blank=True, help_text='ID del dispositivo para cuentas separadas.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='session_token',
            field=models.CharField(blank=True, help_text='Tokens de la mesa para agrupar tickets de una visita.', max_length=100, null=True),
        ),
    ]
