# Generated by Django 6.0.3 on 2026-04-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_quick_service',
            field=models.BooleanField(default=False, help_text='Marcar para bebidas/bar que el mozo puede servir rápido.'),
        ),
    ]
