# Generated by Django 6.0.3 on 2026-05-06 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_is_quick_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Categoría principal de la cual depende esta subcategoría.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category'),
        ),
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. Preparación de Huevos, Elección de Bebida, Extras', max_length=100)),
                ('min_selectable', models.PositiveIntegerField(default=1, help_text='0 para opcional (como adicionales extras), 1 para obligatorio (como término de cocción)')),
                ('max_selectable', models.PositiveIntegerField(default=1, help_text='1 para selección única (radio), >1 para selección múltiple (checkboxes)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_modifier', models.DecimalField(decimal_places=2, default=0.0, help_text='Costo adicional (ej. +3.00 para extras o 0.00 para incluido/gratis)', max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.optiongroup')),
            ],
        ),
    ]
